// English Vocabulary Database
// Version: 1.0
// Last Updated: 2026-02-03
// Source: eng_dict.md

const vocabularyData = {
  // Metadata
  meta: {
    version: "1.0",
    source: "English Vocabulary for Chinese Learners",
    lastUpdated: "2026-02-03"
  },

  // Vocabulary organized by units
  units: {
    "Unit 1": {
      title: "People and Appearance",
      words: [
        { word: "different", phonetic: "/ˈdɪfrənt/", partOfSpeech: "adj.", chinese: "不平常；与众不同；不同的；有区别的", page: "p. 2" },
        { word: "notice", phonetic: "/ˈnəʊtɪs/", partOfSpeech: "v.", chinese: "注意", page: "p. 4" },
        { word: "notice", phonetic: "/ˈnəʊtɪs/", partOfSpeech: "n.", chinese: "通知；注意", page: "p. 4" },
        { word: "swan", phonetic: "/swɒn/", partOfSpeech: "n.", chinese: "天鹅", page: "p. 4" },
        { word: "partner", phonetic: "/ˈpɑːtnə(r)/", partOfSpeech: "n.", chinese: "搭档；同伴", page: "p. 4" },
        { word: "slim", phonetic: "/slɪm/", partOfSpeech: "adj.", chinese: "苗条的；纤细的", page: "p. 4" },
        { word: "fat", phonetic: "/fæt/", partOfSpeech: "adj.", chinese: "肥的；胖的", page: "p. 4" },
        { word: "curly", phonetic: "/ˈkɜːli/", partOfSpeech: "adj.", chinese: "卷曲状的", page: "p. 4" },
        { word: "straight", phonetic: "/streɪt/", partOfSpeech: "adj.", chinese: "直的", page: "p. 4" },
        { word: "T-shirt", phonetic: "/ˈtiː ʃɜːt/", partOfSpeech: "n.", chinese: "T恤衫；短袖汗衫", page: "p. 4" },
        { word: "jeans", phonetic: "/dʒiːnz/", partOfSpeech: "n.", chinese: "牛仔裤", page: "p. 4" },
        { word: "size", phonetic: "/saɪz/", partOfSpeech: "n.", chinese: "大小；尺码", page: "p. 5" },
        { word: "shape", phonetic: "/ʃeɪp/", partOfSpeech: "n.", chinese: "形状；外形", page: "p. 5" },
        { word: "skin", phonetic: "/skɪn/", partOfSpeech: "n.", chinese: "皮肤", page: "p. 5" },
        { word: "special", phonetic: "/ˈspeʃl/", partOfSpeech: "adj.", chinese: "特殊的；特别的", page: "p. 5" },
        { word: "number", phonetic: "/ˈnʌmbə(r)/", partOfSpeech: "n.", chinese: "编号；数字；数量", page: "p. 5" },
        { word: "than", phonetic: "/ðæn; ðən/", partOfSpeech: "prep.", chinese: "比", page: "p. 5" },
        { word: "fair", phonetic: "/feə(r)/", partOfSpeech: "adj.", chinese: "(头发或皮肤）浅色的；白皙的", page: "p. 5" },
        { word: "talent", phonetic: "/ˈtælənt/", partOfSpeech: "n.", chinese: "天才；天赋", page: "p. 6" },
        { word: "programme", phonetic: "/ˈprəʊgræm/", partOfSpeech: "n.", chinese: "节目单；计划；方案；活动安排", page: "p. 6" },
        { word: "hall", phonetic: "/hɔːl/", partOfSpeech: "n.", chinese: "礼堂；大厅", page: "p. 6" },
        { word: "butterfly", phonetic: "/ˈbʌtəflaɪ/", partOfSpeech: "n.", chinese: "蝴蝶", page: "p. 6" },
        { word: "violin", phonetic: "/ˌvaɪəˈlɪn/", partOfSpeech: "n.", chinese: "小提琴", page: "p. 6" },
        { word: "host", phonetic: "/həʊst/", partOfSpeech: "n.", chinese: "节目主持人", page: "p. 6" },
        { word: "sound", phonetic: "/saʊnd/", partOfSpeech: "v.", chinese: "听起来", page: "p. 6" },
        { word: "sound", phonetic: "/saʊnd/", partOfSpeech: "n.", chinese: "声音", page: "p. 6" },
        { word: "excite", phonetic: "/ɪkˈsaɪt/", partOfSpeech: "v.", chinese: "使激动；使兴奋", page: "p. 6" },
        { word: "exciting", phonetic: "/ɪkˈsaɪtɪŋ/", partOfSpeech: "adj.", chinese: "令人兴奋的；令人激动的", page: "p. 6" },
        { word: "anything", phonetic: "/ˈeniθɪŋ/", partOfSpeech: "pron.", chinese: "任何东西；任何事物", page: "p. 6" },
        { word: "someone", phonetic: "/ˈsʌmwʌn/", partOfSpeech: "pron.", chinese: "某人", page: "p. 6" },
        { word: "drum", phonetic: "/drʌm/", partOfSpeech: "v.", chinese: "打鼓", page: "p. 7" },
        { word: "drum", phonetic: "/drʌm/", partOfSpeech: "n.", chinese: "鼓", page: "p. 7" },
        { word: "voice", phonetic: "/vɔɪs/", partOfSpeech: "n.", chinese: "嗓音；说话声；歌唱声", page: "p. 7" },
        { word: "person", phonetic: "/ˈpɜːsn/", partOfSpeech: "n.", chinese: "人；个人", page: "p. 7" },
        { word: "hobby", phonetic: "/ˈhɒbi/", partOfSpeech: "n.", chinese: "业余爱好", page: "p. 7" },
        { word: "personality", phonetic: "/ˌpɜːsəˈnæləti/", partOfSpeech: "n.", chinese: "性格；个性", page: "p. 7" },
        { word: "ability", phonetic: "/əˈbɪləti/", partOfSpeech: "n.", chinese: "才能；本领；能力", page: "p. 7" },
        { word: "easy-going", phonetic: "/ˌiːzi ˈgəʊɪŋ/", partOfSpeech: "adj.", chinese: "随和的", page: "p. 7" },
        { word: "accept", phonetic: "/əkˈsept/", partOfSpeech: "v.", chinese: "接受；同意", page: "p. 8" },
        { word: "peacock", phonetic: "/ˈpiːkɒk/", partOfSpeech: "n.", chinese: "孔雀", page: "p. 8" },
        { word: "wise", phonetic: "/waɪz/", partOfSpeech: "adj.", chinese: "充满智慧的；明智的", page: "p. 8" },
        { word: "nightingale", phonetic: "/ˈnaɪtɪŋgeɪl/", partOfSpeech: "n.", chinese: "夜莺", page: "p. 8" },
        { word: "without", phonetic: "/wɪˈðaʊt/", partOfSpeech: "prep.", chinese: "没有；缺乏", page: "p. 8" },
        { word: "doubt", phonetic: "/daʊt/", partOfSpeech: "n.", chinese: "疑惑；疑问", page: "p. 8" },
        { word: "laugh", phonetic: "/lɑːf/", partOfSpeech: "v.", chinese: "笑；发笑", page: "p. 8" },
        { word: "smile", phonetic: "/smaɪl/", partOfSpeech: "v.", chinese: "微笑；笑", page: "p. 8" },
        { word: "feather", phonetic: "/ˈfeðə(r)/", partOfSpeech: "n.", chinese: "羽毛", page: "p. 8" },
        { word: "colourful", phonetic: "/ˈkʌləfl/", partOfSpeech: "adj.", chinese: "颜色鲜艳的；五彩缤纷的", page: "p. 8" },
        { word: "future", phonetic: "/ˈfjuːtʃə(r)/", partOfSpeech: "n.", chinese: "将来；未来", page: "p. 8" },
        { word: "pat", phonetic: "/pæt/", partOfSpeech: "v.", chinese: "轻拍", page: "p. 8" },
        { word: "skill", phonetic: "/skɪl/", partOfSpeech: "n.", chinese: "技巧；技艺", page: "p. 8" },
        { word: "unique", phonetic: "/juˈniːk/", partOfSpeech: "adj.", chinese: "唯一的；独一无二的", page: "p. 8" },
        { word: "mean", phonetic: "/miːn/", partOfSpeech: "v.", chinese: "意思是", page: "p. 12" },
        { word: "noticeboard", phonetic: "/ˈnəʊtɪsbɔːd/", partOfSpeech: "n.", chinese: "布告栏；布告板", page: "p. 12" },
        { word: "would", phonetic: "/wʊd/", partOfSpeech: "modal v.", chinese: "(客气地建议或邀请）将；将会", page: "p. 12" }
      ]
    },
    "Unit 2": {
      title: "Rules and Transportation",
      words: [
        { word: "rule", phonetic: "/ruːl/", partOfSpeech: "n.", chinese: "规则；规章", page: "p. 16" },
        { word: "underground", phonetic: "/ˈʌndəgraʊnd/", partOfSpeech: "n.", chinese: "地铁；地下铁路系统", page: "p. 18" },
        { word: "lean", phonetic: "/liːn/", partOfSpeech: "v.", chinese: "倚靠；倾斜", page: "p. 18" },
        { word: "litter", phonetic: "/ˈlɪtə(r)/", partOfSpeech: "v.", chinese: "乱扔", page: "p. 18" },
        { word: "litter", phonetic: "/ˈlɪtə(r)/", partOfSpeech: "n.", chinese: "垃圾；废弃物", page: "p. 18" },
        { word: "gap", phonetic: "/gæp/", partOfSpeech: "n.", chinese: "缺口；间隙", page: "p. 18" },
        { word: "else", phonetic: "/els/", partOfSpeech: "adv.", chinese: "其他的；别的", page: "p. 18" },
        { word: "escalator", phonetic: "/ˈeskəleɪtə(r)/", partOfSpeech: "n.", chinese: "自动扶梯", page: "p. 18" },
        { word: "station", phonetic: "/ˈsteɪʃn/", partOfSpeech: "n.", chinese: "车站；(服务）台", page: "p. 18" },
        { word: "announcement", phonetic: "/əˈnaʊnsmənt/", partOfSpeech: "n.", chinese: "公告；通告", page: "p. 19" },
        { word: "passenger", phonetic: "/ˈpæsɪndʒə(r)/", partOfSpeech: "n.", chinese: "乘客；旅客", page: "p. 19" },
        { word: "lift", phonetic: "/lɪft/", partOfSpeech: "n.", chinese: "电梯；升降机", page: "p. 19" },
        { word: "platform", phonetic: "/ˈplætfɔːm/", partOfSpeech: "n.", chinese: "站台", page: "p. 19" },
        { word: "line", phonetic: "/laɪn/", partOfSpeech: "n.", chinese: "线；线条", page: "p. 19" },
        { word: "rush", phonetic: "/rʌʃ/", partOfSpeech: "v.", chinese: "迅速移动；急促", page: "p. 19" },
        { word: "smoke", phonetic: "/sməʊk/", partOfSpeech: "v.", chinese: "吸烟；抽烟", page: "p. 19" },
        { word: "seat", phonetic: "/siːt/", partOfSpeech: "n.", chinese: "座位", page: "p. 19" },
        { word: "anyone", phonetic: "/ˈeniwʌn/", partOfSpeech: "pron.", chinese: "任何人", page: "p. 19" },
        { word: "leave", phonetic: "/liːv/", partOfSpeech: "v.", chinese: "留下；离开", page: "p. 20" },
        { word: "rubbish", phonetic: "/ˈrʌbɪʃ/", partOfSpeech: "n.", chinese: "垃圾；废弃物", page: "p. 20" },
        { word: "glove", phonetic: "/glʌv/", partOfSpeech: "n.", chinese: "手套", page: "p. 20" },
        { word: "broken", phonetic: "/ˈbrəʊkən/", partOfSpeech: "adj.", chinese: "破损的；伤残的", page: "p. 20" },
        { word: "container", phonetic: "/kənˈteɪnə(r)/", partOfSpeech: "n.", chinese: "容器", page: "p. 20" },
        { word: "ready", phonetic: "/ˈredi/", partOfSpeech: "adj.", chinese: "准备好；准备完毕", page: "p. 21" },
        { word: "follow", phonetic: "/ˈfɒləʊ/", partOfSpeech: "v.", chinese: "遵循；跟随", page: "p. 21" },
        { word: "stay", phonetic: "/steɪ/", partOfSpeech: "v.", chinese: "保持；继续是", page: "p. 21" },
        { word: "grow", phonetic: "/grəʊ/", partOfSpeech: "v.", chinese: "逐渐变得；逐渐成为", page: "p. 21" },
        { word: "important", phonetic: "/ɪmˈpɔːtnt/", partOfSpeech: "adj.", chinese: "重要的；有重大影响的", page: "p. 22" },
        { word: "hurrah", phonetic: "/həˈrɑː/", partOfSpeech: "excl.", chinese: "万岁；好哇", page: "p. 22" },
        { word: "model", phonetic: "/ˈmɒdl/", partOfSpeech: "n.", chinese: "模型", page: "p. 22" },
        { word: "pay", phonetic: "/peɪ/", partOfSpeech: "v.", chinese: "(与某些名词结合使用，表示将要做或将付出某事物）", page: "p. 22" },
        { word: "attention", phonetic: "/əˈtenʃn/", partOfSpeech: "n.", chinese: "注意；关注", page: "p. 22" },
        { word: "dream", phonetic: "/driːm/", partOfSpeech: "n.", chinese: "梦；梦想", page: "p. 22" },
        { word: "outing", phonetic: "/ˈaʊtɪŋ/", partOfSpeech: "n.", chinese: "(集体）出外游玩（或学习）；远足", page: "p. 26" },
        { word: "gate", phonetic: "/geɪt/", partOfSpeech: "n.", chinese: "大门", page: "p. 26" }
      ]
    },
    "Unit 3": {
      title: "Festivals and Culture",
      words: [
        { word: "festival", phonetic: "/ˈfestɪvl/", partOfSpeech: "n.", chinese: "节日", page: "p. 30" },
        { word: "across", phonetic: "/əˈkrɒs/", partOfSpeech: "prep.", chinese: "横过；穿过", page: "p. 30" },
        { word: "culture", phonetic: "/ˈkʌltʃə(r)/", partOfSpeech: "n.", chinese: "文化", page: "p. 30" },
        { word: "luck", phonetic: "/lʌk/", partOfSpeech: "n.", chinese: "机遇；命运；运气", page: "p. 32" },
        { word: "spring roll", phonetic: "/ˌsprɪŋ ˈrəʊl/", partOfSpeech: "n.", chinese: "春卷", page: "p. 32" },
        { word: "porridge", phonetic: "/ˈpɒrɪdʒ/", partOfSpeech: "n.", chinese: "粥", page: "p. 32" },
        { word: "lucky", phonetic: "/ˈlʌki/", partOfSpeech: "adj.", chinese: "有好运的；运气好的；幸运的", page: "p. 32" },
        { word: "click", phonetic: "/klɪk/", partOfSpeech: "v.", chinese: "(在计算机屏幕上用鼠标）点击，单击", page: "p. 32" },
        { word: "eve", phonetic: "/iːv/", partOfSpeech: "n.", chinese: "前夜；前夕", page: "p. 33" },
        { word: "tradition", phonetic: "/trəˈdɪʃn/", partOfSpeech: "n.", chinese: "传统", page: "p. 33" },
        { word: "country", phonetic: "/ˈkʌntri/", partOfSpeech: "n.", chinese: "国家", page: "p. 33" },
        { word: "wealth", phonetic: "/welθ/", partOfSpeech: "n.", chinese: "钱财；财富", page: "p. 33" },
        { word: "hope", phonetic: "/həʊp/", partOfSpeech: "v.", chinese: "希望；期望（某事发生）", page: "p. 33" },
        { word: "pass", phonetic: "/pɑːs/", partOfSpeech: "v.", chinese: "给；递；传递", page: "p. 33" },
        { word: "midnight", phonetic: "/ˈmɪdnaɪt/", partOfSpeech: "n.", chinese: "午夜", page: "p. 33" },
        { word: "international", phonetic: "/ˌɪntəˈnæʃnəl/", partOfSpeech: "adj.", chinese: "国际的", page: "p. 34" },
        { word: "event", phonetic: "/ɪˈvent/", partOfSpeech: "n.", chinese: "公开活动；发生的事情", page: "p. 34" },
        { word: "square", phonetic: "/skweə(r)/", partOfSpeech: "n.", chinese: "广场", page: "p. 34" },
        { word: "symphony", phonetic: "/ˈsɪmfəni/", partOfSpeech: "n.", chinese: "交响乐；交响曲", page: "p. 34" },
        { word: "theatre", phonetic: "/ˈθɪətə(r)/", partOfSpeech: "n.", chinese: "戏院；剧场；露天剧场", page: "p. 34" },
        { word: "firework", phonetic: "/ˈfaɪəwɜːk/", partOfSpeech: "n.", chinese: "烟火；烟花", page: "p. 34" },
        { word: "concert", phonetic: "/ˈkɒnsət/", partOfSpeech: "n.", chinese: "音乐会；演奏会", page: "p. 34" },
        { word: "prince", phonetic: "/prɪns/", partOfSpeech: "n.", chinese: "王子", page: "p. 34" },
        { word: "check", phonetic: "/tʃek/", partOfSpeech: "v.", chinese: "查明；查看；核实；弄确实", page: "p. 34" },
        { word: "information", phonetic: "/ˌɪnfəˈmeɪʃn/", partOfSpeech: "n.", chinese: "信息；消息；情报；资料；资讯", page: "p. 34" },
        { word: "since", phonetic: "/sɪns/", partOfSpeech: "prep.", chinese: "自……以来；自……以后", page: "p. 34" },
        { word: "performance", phonetic: "/pəˈfɔːməns/", partOfSpeech: "n.", chinese: "表演", page: "p. 34" },
        { word: "really", phonetic: "/ˈrɪəli/", partOfSpeech: "adv.", chinese: "事实上；真正地", page: "p. 35" },
        { word: "musical", phonetic: "/ˈmjuːzɪkl/", partOfSpeech: "adj.", chinese: "音乐的", page: "p. 35" },
        { word: "musical", phonetic: "/ˈmjuːzɪkl/", partOfSpeech: "n.", chinese: "音乐剧", page: "p. 35" },
        { word: "perform", phonetic: "/pəˈfɔːm/", partOfSpeech: "v.", chinese: "表演；演出", page: "p. 35" },
        { word: "invite", phonetic: "/ɪnˈvaɪt/", partOfSpeech: "v.", chinese: "邀请", page: "p. 35" },
        { word: "celebrate", phonetic: "/ˈselɪbreɪt/", partOfSpeech: "v.", chinese: "庆祝；庆贺", page: "p. 36" },
        { word: "calendar", phonetic: "/ˈkælɪndə(r)/", partOfSpeech: "n.", chinese: "日历；历法", page: "p. 36" },
        { word: "reunion", phonetic: "/ˌriːˈjuːniən/", partOfSpeech: "n.", chinese: "重逢；团聚", page: "p. 36" },
        { word: "full", phonetic: "/fʊl/", partOfSpeech: "adj.", chinese: "满的", page: "p. 36" },
        { word: "post", phonetic: "/pəʊst/", partOfSpeech: "v.", chinese: "发帖；寄；邮寄", page: "p. 36" },
        { word: "mostly", phonetic: "/ˈməʊstli/", partOfSpeech: "adv.", chinese: "主要地；一般地；通常", page: "p. 36" },
        { word: "tonight", phonetic: "/təˈnaɪt/", partOfSpeech: "adv.", chinese: "今晚", page: "p. 36" },
        { word: "harvest", phonetic: "/ˈhɑːvɪst/", partOfSpeech: "n.", chinese: "收获；收获季节", page: "p. 36" },
        { word: "traditional", phonetic: "/trəˈdɪʃənl/", partOfSpeech: "adj.", chinese: "传统的；习俗的", page: "p. 36" },
        { word: "nut", phonetic: "/nʌt/", partOfSpeech: "n.", chinese: "坚果", page: "p. 36" },
        { word: "sugar", phonetic: "/ˈʃʊgə(r)/", partOfSpeech: "n.", chinese: "食糖", page: "p. 36" },
        { word: "experience", phonetic: "/ɪkˈspɪəriəns/", partOfSpeech: "n.", chinese: "经历；经验", page: "p. 40" },
        { word: "meal", phonetic: "/miːl/", partOfSpeech: "n.", chinese: "早（或午、晚）餐；一顿饭", page: "p. 40" },
        { word: "count", phonetic: "/kaʊnt/", partOfSpeech: "v.", chinese: "数数；计算", page: "p. 40" }
      ]
    },
    "Unit 4": {
      title: "Weather and Climate",
      words: [
        { word: "search", phonetic: "/sɜːtʃ/", partOfSpeech: "v.", chinese: "搜索；搜寻；搜查；查找", page: "p. 46" },
        { word: "airport", phonetic: "/ˈeəpɔːt/", partOfSpeech: "n.", chinese: "机场", page: "p. 46" },
        { word: "location", phonetic: "/ləʊˈkeɪʃn/", partOfSpeech: "n.", chinese: "地方；地点；位置", page: "p. 46" },
        { word: "capital", phonetic: "/ˈkæpɪtl/", partOfSpeech: "n.", chinese: "首都；国都", page: "p. 46" },
        { word: "wet", phonetic: "/wet/", partOfSpeech: "adj.", chinese: "湿的；潮湿的", page: "p. 46" },
        { word: "foggy", phonetic: "/ˈfɒgi/", partOfSpeech: "adj.", chinese: "有雾的", page: "p. 46" },
        { word: "north", phonetic: "/nɔːθ/", partOfSpeech: "n.", chinese: "北；北方", page: "p. 46" },
        { word: "north", phonetic: "/nɔːθ/", partOfSpeech: "adv.", chinese: "向北；朝北", page: "p. 46" },
        { word: "quite", phonetic: "/kwaɪt/", partOfSpeech: "adv.", chinese: "相当；非常", page: "p. 46" },
        { word: "temperature", phonetic: "/ˈtemprətʃə(r)/", partOfSpeech: "n.", chinese: "温度；气温", page: "p. 46" },
        { word: "drop", phonetic: "/drɒp/", partOfSpeech: "v.", chinese: "降低；减少", page: "p. 46" },
        { word: "degree", phonetic: "/dɪˈgriː/", partOfSpeech: "n.", chinese: "度；度数", page: "p. 46" },
        { word: "Celsius", phonetic: "/ˈselsiəs/", partOfSpeech: "adj.", chinese: "摄氏的", page: "p. 46" },
        { word: "dry", phonetic: "/draɪ/", partOfSpeech: "adj.", chinese: "干的；干燥的", page: "p. 46" },
        { word: "south", phonetic: "/saʊθ/", partOfSpeech: "n.", chinese: "南部；南方", page: "p. 46" },
        { word: "south", phonetic: "/saʊθ/", partOfSpeech: "adv.", chinese: "向南；朝南", page: "p. 46" },
        { word: "still", phonetic: "/stɪl/", partOfSpeech: "adv.", chinese: "还；仍然", page: "p. 46" },
        { word: "wind", phonetic: "/wɪnd/", partOfSpeech: "n.", chinese: "风", page: "p. 47" },
        { word: "cloud", phonetic: "/klaʊd/", partOfSpeech: "n.", chinese: "云；云朵", page: "p. 47" },
        { word: "fog", phonetic: "/fɒg/", partOfSpeech: "n.", chinese: "雾", page: "p. 47" },
        { word: "skate", phonetic: "/skeɪt/", partOfSpeech: "v.", chinese: "滑冰；溜冰", page: "p. 48" },
        { word: "picnic", phonetic: "/ˈpɪknɪk/", partOfSpeech: "n.", chinese: "野餐", page: "p. 48" },
        { word: "sunshine", phonetic: "/ˈsʌnʃaɪn/", partOfSpeech: "n.", chinese: "阳光；日光", page: "p. 49" },
        { word: "hate", phonetic: "/heɪt/", partOfSpeech: "v.", chinese: "讨厌；憎恶", page: "p. 49" },
        { word: "extreme", phonetic: "/ɪkˈstriːm/", partOfSpeech: "adj.", chinese: "极度的；极大的", page: "p. 50" },
        { word: "news", phonetic: "/njuːz/", partOfSpeech: "n.", chinese: "媒体对重要事情的报道；新闻", page: "p. 50" },
        { word: "heat", phonetic: "/hiːt/", partOfSpeech: "n.", chinese: "热；高温", page: "p. 50" },
        { word: "wave", phonetic: "/weɪv/", partOfSpeech: "n.", chinese: "海浪；波浪", page: "p. 50" },
        { word: "heatwave", phonetic: "/ˈhiːtweɪv/", partOfSpeech: "n.", chinese: "酷热期；热浪", page: "p. 50" },
        { word: "hit", phonetic: "/hɪt/", partOfSpeech: "v.", chinese: "达到（某水平）", page: "p. 50" },
        { word: "several", phonetic: "/ˈsevrəl/", partOfSpeech: "det.", chinese: "几个；数个", page: "p. 50" },
        { word: "break", phonetic: "/breɪk/", partOfSpeech: "v.", chinese: "打破；破；裂；碎", page: "p. 50" },
        { word: "record", phonetic: "/ˈrekɔːd/", partOfSpeech: "n.", chinese: "纪录；记录", page: "p. 50" },
        { word: "record", phonetic: "/rɪˈkɔːd/", partOfSpeech: "v.", chinese: "记录", page: "p. 50" },
        { word: "reach", phonetic: "/riːtʃ/", partOfSpeech: "v.", chinese: "增加到；达到", page: "p. 50" },
        { word: "area", phonetic: "/ˈeəriə/", partOfSpeech: "n.", chinese: "(地方、城市、国家、世界的）地区，地域", page: "p. 50" },
        { word: "runway", phonetic: "/ˈrʌnweɪ/", partOfSpeech: "n.", chinese: "飞机跑道", page: "p. 50" },
        { word: "action", phonetic: "/ˈækʃn/", partOfSpeech: "n.", chinese: "行动；行为过程", page: "p. 50" },
        { word: "pupil", phonetic: "/ˈpjuːpl/", partOfSpeech: "n.", chinese: "学生；小学生", page: "p. 50" },
        { word: "uniform", phonetic: "/ˈjuːnɪfɔːm/", partOfSpeech: "n.", chinese: "制服；校服", page: "p. 50" },
        { word: "indoors", phonetic: "/ˌɪnˈdɔːz/", partOfSpeech: "adv.", chinese: "在室内", page: "p. 50" },
        { word: "leaf", phonetic: "/liːf/", partOfSpeech: "n.", chinese: "叶子", page: "p. 50" },
        { word: "fact", phonetic: "/fækt/", partOfSpeech: "n.", chinese: "现实；实际情况", page: "p. 50" },
        { word: "average", phonetic: "/ˈævərɪdʒ/", partOfSpeech: "adj.", chinese: "平均的", page: "p. 50" },
        { word: "increase", phonetic: "/ɪnˈkriːs/", partOfSpeech: "v.", chinese: "增长；增加", page: "p. 50" },
        { word: "coal", phonetic: "/kəʊl/", partOfSpeech: "n.", chinese: "煤", page: "p. 50" },
        { word: "cause", phonetic: "/kɔːz/", partOfSpeech: "v.", chinese: "引起；使发生", page: "p. 50" },
        { word: "cause", phonetic: "/kɔːz/", partOfSpeech: "n.", chinese: "原因；事业", page: "p. 50" },
        { word: "worse", phonetic: "/wɜːs/", partOfSpeech: "adj.", chinese: "(bad的比较级）更差的；更糟的", page: "p. 50" },
        { word: "soon", phonetic: "/suːn/", partOfSpeech: "adv.", chinese: "很快；马上；不久", page: "p. 54" },
        { word: "regards", phonetic: "/rɪˈgɑːdz/", partOfSpeech: "n.", chinese: "致意；问候", page: "p. 54" }
      ]
    },
    "Unit 5": {
      title: "Environment and Sustainability",
      words: [
        { word: "neighbourhood", phonetic: "/ˈneɪbəhʊd/", partOfSpeech: "n.", chinese: "街区；邻近的地方", page: "p. 58" },
        { word: "build", phonetic: "/bɪld/", partOfSpeech: "v.", chinese: "创建；建造", page: "p. 60" },
        { word: "reduce", phonetic: "/rɪˈdjuːs/", partOfSpeech: "v.", chinese: "减少；缩小", page: "p. 60" },
        { word: "reuse", phonetic: "/ˌriːˈjuːz/", partOfSpeech: "v.", chinese: "重复使用", page: "p. 60" },
        { word: "recycle", phonetic: "/ˌriːˈsaɪkl/", partOfSpeech: "v.", chinese: "回收利用", page: "p. 60" },
        { word: "bottle", phonetic: "/ˈbɒtl/", partOfSpeech: "n.", chinese: "瓶子", page: "p. 60" },
        { word: "repair", phonetic: "/rɪˈpeə(r)/", partOfSpeech: "v.", chinese: "修理；修补", page: "p. 60" },
        { word: "item", phonetic: "/ˈaɪtəm/", partOfSpeech: "n.", chinese: "一件物品", page: "p. 60" },
        { word: "sort", phonetic: "/sɔːt/", partOfSpeech: "v.", chinese: "整理；把……分类", page: "p. 60" },
        { word: "cloth", phonetic: "/klɒθ/", partOfSpeech: "n.", chinese: "织物；布料", page: "p. 60" },
        { word: "pick", phonetic: "/pɪk/", partOfSpeech: "v.", chinese: "拿起；挑选；选择", page: "p. 60" },
        { word: "plastic", phonetic: "/ˈplæstɪk/", partOfSpeech: "adj.", chinese: "塑料的", page: "p. 61" },
        { word: "plastic", phonetic: "/ˈplæstɪk/", partOfSpeech: "n.", chinese: "塑料", page: "p. 61" },
        { word: "waste", phonetic: "/weɪst/", partOfSpeech: "n.", chinese: "废物；垃圾", page: "p. 61" },
        { word: "waste", phonetic: "/weɪst/", partOfSpeech: "v.", chinese: "浪费；滥用", page: "p. 61" },
        { word: "electricity", phonetic: "/ɪˌlekˈtrɪsəti/", partOfSpeech: "n.", chinese: "电；电能", page: "p. 61" },
        { word: "tap", phonetic: "/tæp/", partOfSpeech: "n.", chinese: "水龙头", page: "p. 62" },
        { word: "brush", phonetic: "/brʌʃ/", partOfSpeech: "v.", chinese: "(用刷子）刷净，刷亮，刷平顺", page: "p. 62" },
        { word: "tooth", phonetic: "/tuːθ/", partOfSpeech: "n.", chinese: "牙；齿", page: "p. 62" },
        { word: "bin", phonetic: "/bɪn/", partOfSpeech: "n.", chinese: "垃圾箱", page: "p. 62" },
        { word: "save", phonetic: "/seɪv/", partOfSpeech: "v.", chinese: "节省；节约；救", page: "p. 62" },
        { word: "mix", phonetic: "/mɪks/", partOfSpeech: "v.", chinese: "混合；融合", page: "p. 62" },
        { word: "reusable", phonetic: "/ˌriːˈjuːzəbl/", partOfSpeech: "adj.", chinese: "可重复使用的；可再次使用的", page: "p. 63" },
        { word: "store", phonetic: "/stɔː(r)/", partOfSpeech: "n.", chinese: "商店；店铺", page: "p. 63" },
        { word: "even", phonetic: "/ˈiːvn/", partOfSpeech: "adv.", chinese: "(强调出乎意料）甚至，连，即使", page: "p. 63" },
        { word: "huge", phonetic: "/hjuːdʒ/", partOfSpeech: "adj.", chinese: "巨大的；极多的；程度高的", page: "p. 64" },
        { word: "government", phonetic: "/ˈgʌvənmənt/", partOfSpeech: "n.", chinese: "政府；内阁", page: "p. 64" },
        { word: "encourage", phonetic: "/ɪnˈkʌrɪdʒ/", partOfSpeech: "v.", chinese: "支持；鼓励；激励", page: "p. 64" },
        { word: "public", phonetic: "/ˈpʌblɪk/", partOfSpeech: "adj.", chinese: "公共的；公立的", page: "p. 64" },
        { word: "transport", phonetic: "/ˈtrænspɔːt/", partOfSpeech: "n.", chinese: "交通车辆；旅行方式", page: "p. 64" },
        { word: "environmental", phonetic: "/ɪnˌvaɪrənˈmentl/", partOfSpeech: "adj.", chinese: "环境的", page: "p. 64" },
        { word: "electric", phonetic: "/ɪˈlektrɪk/", partOfSpeech: "adj.", chinese: "电的；电动的", page: "p. 64" },
        { word: "building", phonetic: "/ˈbɪldɪŋ/", partOfSpeech: "n.", chinese: "建筑物；房子；楼房", page: "p. 64" },
        { word: "low", phonetic: "/ləʊ/", partOfSpeech: "adj.", chinese: "低于平均水平的；低的；矮的", page: "p. 64" },
        { word: "energy", phonetic: "/ˈenədʒi/", partOfSpeech: "n.", chinese: "能源", page: "p. 64" },
        { word: "low-energy", phonetic: "/ləʊ ˈenədʒi/", partOfSpeech: "adj.", chinese: "低能耗的", page: "p. 64" },
        { word: "however", phonetic: "/haʊˈevə(r)/", partOfSpeech: "adv.", chinese: "然而", page: "p. 64" },
        { word: "alone", phonetic: "/əˈləʊn/", partOfSpeech: "adv.", chinese: "独自", page: "p. 64" },
        { word: "planet", phonetic: "/ˈplænɪt/", partOfSpeech: "n.", chinese: "行星", page: "p. 64" },
        { word: "mankind", phonetic: "/mænˈkaɪnd/", partOfSpeech: "n.", chinese: "人类", page: "p. 64" },
        { word: "daily", phonetic: "/ˈdeɪli/", partOfSpeech: "adj.", chinese: "每日的；日常的", page: "p. 68" }
      ]
    },
    "Unit 6": {
      title: "Science and Achievements",
      words: [
        { word: "changer", phonetic: "/ˈtʃeɪndʒə(r)/", partOfSpeech: "n.", chinese: "改变者；改进者", page: "p. 74" },
        { word: "scientist", phonetic: "/ˈsaɪəntɪst/", partOfSpeech: "n.", chinese: "科学家", page: "p. 74" },
        { word: "change", phonetic: "/tʃeɪndʒ/", partOfSpeech: "v.", chinese: "改变；变化", page: "p. 74" },
        { word: "publish", phonetic: "/ˈpʌblɪʃ/", partOfSpeech: "v.", chinese: "出版；发行", page: "p. 74" },
        { word: "theory", phonetic: "/ˈθɪəri/", partOfSpeech: "n.", chinese: "学说；理论", page: "p. 74" },
        { word: "invent", phonetic: "/ɪnˈvent/", partOfSpeech: "v.", chinese: "发明；创造", page: "p. 74" },
        { word: "inexpensive", phonetic: "/ˌɪnɪkˈspensɪv/", partOfSpeech: "adj.", chinese: "廉价的；不昂贵的", page: "p. 74" },
        { word: "bulb", phonetic: "/bʌlb/", partOfSpeech: "n.", chinese: "电灯泡", page: "p. 74" },
        { word: "discover", phonetic: "/dɪˈskʌvə(r)/", partOfSpeech: "v.", chinese: "发现", page: "p. 74" },
        { word: "general", phonetic: "/ˈdʒenrəl/", partOfSpeech: "adj.", chinese: "全体的；普遍的；总的", page: "p. 74" },
        { word: "smart", phonetic: "/smɑːt/", partOfSpeech: "adj.", chinese: "聪明的；机敏的", page: "p. 75" },
        { word: "inventor", phonetic: "/ɪnˈventə(r)/", partOfSpeech: "n.", chinese: "发明者；发明家", page: "p. 75" },
        { word: "real", phonetic: "/ˈrɪəl/", partOfSpeech: "adj.", chinese: "真正的", page: "p. 75" },
        { word: "power", phonetic: "/ˈpaʊə(r)/", partOfSpeech: "n.", chinese: "电；电力供应", page: "p. 75" },
        { word: "die", phonetic: "/daɪ/", partOfSpeech: "v.", chinese: "死亡", page: "p. 75" },
        { word: "successful", phonetic: "/səkˈsesfl/", partOfSpeech: "adj.", chinese: "达到目的的；有成效的；获得成功的", page: "p. 75" },
        { word: "invention", phonetic: "/ɪnˈvenʃn/", partOfSpeech: "n.", chinese: "发明；创造", page: "p. 75" },
        { word: "saver", phonetic: "/ˈseɪvə(r)/", partOfSpeech: "n.", chinese: "救助者；救星", page: "p. 76" },
        { word: "medicine", phonetic: "/ˈmedsn/", partOfSpeech: "n.", chinese: "医学；药", page: "p. 76" },
        { word: "spend", phonetic: "/spend/", partOfSpeech: "v.", chinese: "花（时间）；度过", page: "p. 76" },
        { word: "sick", phonetic: "/sɪk/", partOfSpeech: "adj.", chinese: "生病的；有病的", page: "p. 76" },
        { word: "penicillin", phonetic: "/ˌpenɪˈsɪlɪn/", partOfSpeech: "n.", chinese: "青霉素；盘尼西林", page: "p. 76" },
        { word: "soldier", phonetic: "/ˈsəʊldʒə(r)/", partOfSpeech: "n.", chinese: "军人；士兵", page: "p. 76" },
        { word: "lose", phonetic: "/luːz/", partOfSpeech: "v.", chinese: "遗失；丢失", page: "p. 76" },
        { word: "admire", phonetic: "/ədˈmaɪə(r)/", partOfSpeech: "v.", chinese: "钦佩；赞赏；仰慕", page: "p. 76" },
        { word: "herb", phonetic: "/hɜːb/", partOfSpeech: "n.", chinese: "药草；芳草", page: "p. 76" },
        { word: "pardon", phonetic: "/ˈpɑːdn/", partOfSpeech: "excl.", chinese: "请再说一遍", page: "p. 77" },
        { word: "pain", phonetic: "/peɪn/", partOfSpeech: "n.", chinese: "疼痛", page: "p. 77" },
        { word: "beg", phonetic: "/beg/", partOfSpeech: "v.", chinese: "乞讨；乞求", page: "p. 77" },
        { word: "storyteller", phonetic: "/ˈstɔːritelə(r)/", partOfSpeech: "n.", chinese: "讲故事的人", page: "p. 78" },
        { word: "poem", phonetic: "/ˈpəʊɪm/", partOfSpeech: "n.", chinese: "诗", page: "p. 78" },
        { word: "act", phonetic: "/ækt/", partOfSpeech: "v.", chinese: "表演", page: "p. 78" },
        { word: "act", phonetic: "/ækt/", partOfSpeech: "n.", chinese: "行为", page: "p. 78" },
        { word: "poor", phonetic: "/pɔː(r)/", partOfSpeech: "adj.", chinese: "贫穷的", page: "p. 78" },
        { word: "tragedy", phonetic: "/ˈtrædʒədi/", partOfSpeech: "n.", chinese: "悲剧；悲剧作品", page: "p. 78" },
        { word: "create", phonetic: "/kriˈeɪt/", partOfSpeech: "v.", chinese: "创造；创作", page: "p. 78" },
        { word: "character", phonetic: "/ˈkærəktə(r)/", partOfSpeech: "n.", chinese: "角色", page: "p. 78" },
        { word: "stage", phonetic: "/steɪdʒ/", partOfSpeech: "n.", chinese: "舞台", page: "p. 78" },
        { word: "million", phonetic: "/ˈmɪljən/", partOfSpeech: "num.", chinese: "一百万", page: "p. 78" },
        { word: "mark", phonetic: "/mɑːk/", partOfSpeech: "v.", chinese: "做记号；做标记", page: "p. 82" },
        { word: "mark", phonetic: "/mɑːk/", partOfSpeech: "n.", chinese: "标记；记号", page: "p. 82" },
        { word: "level", phonetic: "/ˈlevl/", partOfSpeech: "n.", chinese: "水平；标准", page: "p. 82" },
        { word: "until", phonetic: "/ənˈtɪl/", partOfSpeech: "conj.", chinese: "(=till）直到……为止", page: "p. 82" },
        { word: "weigh", phonetic: "/weɪ/", partOfSpeech: "v.", chinese: "称重量；权衡", page: "p. 82" },
        { word: "weight", phonetic: "/weɪt/", partOfSpeech: "n.", chinese: "重量；分量", page: "p. 82" },
        { word: "stamp", phonetic: "/stæmp/", partOfSpeech: "n.", chinese: "邮票", page: "p. 85" }
      ]
    }
  },

  // Part of speech options for the quiz
  partsOfSpeech: ["n.", "v.", "adj.", "adv.", "prep.", "pron.", "conj.", "num.", "det.", "excl.", "modal v."]
};

// Export (compatible with multiple usage patterns)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = vocabularyData;
}
